trigger:

- master

jobs: 
- job: Windows
  strategy:
    matrix:
      vs2019:
        image: windows-2019

  pool: 
    vmImage: $[ variables['image'] ]

  variables:
    QT_VERSION: '5.12.6'
    QLI_VERSION: '2019.05.26.1'
    QLI_OUT_DIR: '.\deps\Qt'
    QLI_BASE_URL: 'http://mirrors.ocf.berkeley.edu/qt/online/qtsdkrepository/'
    QT_PATH: '$(Build.Repository.LocalPath)\$(QLI_OUT_DIR)\$(QT_VERSION)\msvc2017_64'
    QT_PATH_32: '$(Build.Repository.LocalPath)\$(QLI_OUT_DIR)\$(QT_VERSION)\msvc2017'
    BONJOUR_SDK_HOME: '.\deps\Bonjour SDK'
    BONJOUR_SDK_LIB: '$(BONJOUR_SDK_HOME)\Lib\x64\dnssd.lib'
    BONJOUR_SDK_LIB_32: '$(BONJOUR_SDK_HOME)\Lib\Win32\dnssd.lib'

  steps:
#As the official installer is rather 'slow' use an unofficial installer QLI
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        New-Item -Force -ItemType Directory -Path ".\deps\"
        $client = new-object System.Net.WebClient
        $client.DownloadFile("https://github.com/nelsonjchen/qli-installer/archive/v$(QLI_VERSION).zip","deps\qli.zip")
    displayName: 'Downloading QLI v$(QLI_VERSION)'

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        New-Item -Force -ItemType Directory -Path ".\deps\"
        $client = new-object System.Net.WebClient
        $client.DownloadFile("https://binaries.symless.com/bonjour/Bonjour+SDK.zip",".\deps\bonjoursdk.zip")
        $client.DownloadFile("https://binaries.symless.com/bonjour/Bonjour64.msi",".\deps\Bonjour64.msi")
    displayName: 'Downloading Bonjour SKD'

  - task: ExtractFiles@1
    inputs:
      archiveFilePatterns: './deps/*.zip'
      destinationFolder: './deps/'
      cleanDestinationFolder: false
    displayName: 'Extracting zips'

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: 'pip install -r .\deps\qli-installer-$(QLI_VERSION)\requirements.txt'
    displayName: 'Install QLI requirements'

  - task: PythonScript@0
    inputs:
      scriptSource: 'filePath'
      scriptPath: '.\deps\qli-installer-$(QLI_VERSION)\qli-installer.py'
      arguments: '$(QT_VERSION) windows desktop win64_msvc2017_64'
    displayName: 'Installing QT $(QT_VERSION) x64'

  - task: PythonScript@0
    inputs:
      scriptSource: 'filePath'
      scriptPath: '.\deps\qli-installer-$(QLI_VERSION)\qli-installer.py'
      arguments: '$(QT_VERSION) windows desktop win32_msvc2017'
    displayName: 'Installing QT $(QT_VERSION) x32'

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        Get-ChildItem '.\deps'
        msiexec.exe /i ${pwd}\deps\Bonjour64.msi INSTALLDIR="${pwd}\deps\Bonjour" /qb
    displayName: 'Installing bonjour SDK'

  - script: |
      mkdir build64
      cd build64
      cmake -G "Visual Studio 16 2019" -A x64 -V -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=$(QT_PATH) -DDNSSD_LIB=$(BONJOUR_SDK_LIB) ..
    displayName: 'Cmake x64'

  - script: |
      mkdir build32
      cd build32
      cmake -G "Visual Studio 16 2019" -A Win32 -V -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=$(QT_PATH_32) -DDNSSD_LIB=$(BONJOUR_SDK_LIB_32)  ..
    displayName: 'Cmake x86'

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        Get-Content -Path build64\src\gui\synergy.vcxproj
        Get-ChildItem -Path "D:\a\1\s\src\gui\.\deps\Bonjour SDK\Include" -Recurse -Depth 6 -Directory -Force -ErrorAction SilentlyContinue | Select-Object FullName

  - task: MSBuild@1
    inputs:
      solution: 'build64/synergy-core.sln'
      msbuildVersion: '16.0'
      msbuildArchitecture: 'x64'
      platform: 'x64'
      configuration: 'Release'
      msbuildArguments: '/m'
      maximumCpuCount: true
    displayName: 'Compiling x64'

  - task: MSBuild@1
    inputs:
      solution: 'build32/synergy-core.sln'
      msbuildVersion: '16.0'
      msbuildArchitecture: 'x86'
      platform: 'Win32'
      configuration: 'Release'
      msbuildArguments: '/m'
      maximumCpuCount: true
    displayName: 'Compiling x86'