# SPDX-FileCopyrightText: 2025 Chris Rizzitello <sithlord48@gmail.com>
# SPDX-License-Identifier: MIT

version = 1
SPDX-PackageName = "deskflow"
SPDX-PackageSupplier = "Deskflow Devs"
SPDX-PackageDownloadLocation = "https://github.com/deskflow/deskflow"

[[annotations]]
path = [
   ".github/**"
 , ".clang-format"
 , ".editorconfig"
 , ".gitattributes"
 , ".gitignore"
 , "cspell.json"
 , "sonar-project.properties"
 , "cmake/vcpkg.json.in"
 , "**/*.md"
 , "doc/**"
 , "deploy/linux/flatpak/**"
 , "deploy/linux/org.deskflow.deskflow.metainfo.xml"
 , "deploy/windows/wix-patch.xml.in"
 , "src/apps/deskflow-client/deskflow-client.exe.manifest"
 , "src/apps/deskflow-core/deskflow-core.exe.manifest"
 , "src/apps/deskflow-server/deskflow-server.exe.manifest"
 , "src/apps/res/manpage.txt"
 , "src/apps/res/deskflow.plist.in"
 , "translations/*.ts"
]
SPDX-FileCopyrightText = "Deskflow Developers"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
   "deploy/mac/dmg-background.tiff"
 , "deploy/mac/dmg-volume.icns"
 , "deploy/linux/org.deskflow.deskflow.png"
 , "deploy/windows/wix-banner.png"
 , "deploy/windows/wix-dialog.png"
 , "src/apps/res/icons/deskflow-**/apps/64/deskflow*.svg"
 , "src/apps/res/image/welcome.png"
 , "src/apps/res/Deskflow.icns"
 , "src/apps/res/deskflow.ico"
 , "src/apps/res/deskflow.qrc"
]
SPDX-FileCopyrightText = "Deskflow Developers"
SPDX-License-Identifier = "GPL-2.0-only"

[[annotations]]
path = "src/apps/res/icons/deskflow-**/**/**/**.svg"
SPDX-FileCopyrightText = "Kde Breeze Icons"
SPDX-License-Identifier = "LGPL-2.1-only"

[[annotations]]
path = "src/apps/res/icons/deskflow-**/index.theme"
SPDX-FileCopyrightText = "Chris Rizzitello <sithlord48@gmail.com>"
SPDX-License-Identifier = "LGPL-2.1-only"

[[annotations]]
path = [
   "src/lib/gui/MainWindow.ui"
 , "src/lib/gui/dialogs/*.ui"
]
SPDX-FileCopyrightText = "Deskflow Developers"
SPDX-License-Identifier = "GPL-2.0-only WITH LicenseRef-OpenSSL-Exception"
