name: Ubuntu - Core

on:
  release:
    types: [created]

jobs:
  build-core-ubuntu:
    runs-on: ubuntu-latest
    container: symless/synergy-core:ubuntu${{ matrix.distro }}
    env:
      GIT_COMMIT: ${{ github.sha }}
      SYNERGY_NO_LEGACY: "1"
      SYNERGY_NO_TESTS: "1"
    strategy:
      matrix:
        distro: ["20.04", "21.04", "18.04"]
        flag: ["-j"]
        include:
          - distro: "16.04"
            flag: "-j1"

    name: ubuntu${{ matrix.distro }}

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          . ./version
          make ${{ matrix.flag }}

      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_S3_UPLOAD_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_S3_UPLOAD_SECRET }}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: ./build/bin
          destination_dir: "./synergy3/latest/Ubuntu_${{matrix.distro}}/"
