name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "00 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

        stale-issue-message: "This issue has been automatically marked as stale due to inactivity. It will be closed if no further activity occurs. Thank you for your contributions."
        stale-pr-message: "This PR has been automatically marked as stale due to inactivity. It will be closed if no further activity occurs. Thank you for your contributions."

        close-issue-message: "This issue will now be closed due to inactivty. It may be reopened if the demand indicates it should be."
        close-pr-message: "This PR will now be closed due to inactivty. It may be reopened if the demand indicates it should be."

        days-before-stale: 60
        days-before-close: 7

        stale-issue-label: "no-issue-activity"
        stale-pr-label: "no-pr-activity"

        exempt-issue-labels: "work-in-progress,security,critical"
        exempt-pr-labels: "awaiting-approval,work-in-progress"
